"""empty message

Revision ID: a3b6f6b05695
Revises: 
Create Date: 2020-06-19 14:33:04.507018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b6f6b05695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('People', 'fun')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('People', sa.Column('fun', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
